FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine AS production
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
# Install only production deps for the runtime image
RUN npm install --omit=dev
EXPOSE 3001
CMD ["node", "dist/src/main"]
